version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: safedocs-postgres
    environment:
      POSTGRES_DB: safedocs
      POSTGRES_USER: safedocs_user
      POSTGRES_PASSWORD: safedocs_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U safedocs_user -d safedocs"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: safedocs-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  ipfs:
    image: ipfs/kubo:latest
    container_name: safedocs-ipfs
    ports:
      - "8080:8080"  # Gateway
      - "5001:5001"  # API
    volumes:
      - ipfs_data:/data/ipfs
    environment:
      - IPFS_PROFILE=server
    healthcheck:
      test: ["CMD-SHELL", "ipfs id"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
  redis_data:
  ipfs_data: